<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>lego2stl</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lego2STL.Core\Lego2STL.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.11" />
  </ItemGroup>

</Project>
