namespace Lego2STL.Core.Text;

/// <summary>
/// Every piece of text the tool shows.
/// </summary>
/// <remarks>
/// An enum rather than loose strings so that a missing translation is a test failure instead
/// of a phrase that silently stays English. <see cref="Strings"/> holds one table per
/// language, and the suite checks that every value here appears in all of them with matching
/// placeholders.
/// </remarks>
public enum TextKey
{
    // The parts list's column headings. These follow the display language, and every
    // wording the tool has ever written is still accepted on the way back in.
    CsvId,
    CsvLegoCode,
    CsvBrickLinkCode,
    CsvColourName,
    CsvRgb,
    CsvQuantity,

    // Units and small shared words.
    Millimetres,
    On,
    Off,
    Yes,
    No,
    None,

    // Reports.
    ReportRunTitle,
    ReportShapeTitle,
    ReportPlateTitle,
    ReportInput,
    ReportPages,
    ReportColourNumbering,
    ReportReading,
    ReportEntriesRead,
    ReportPartsList,
    ReportTotals,
    ReportTotalEntries,
    ReportTotalPieces,
    ReportTotalDistinctParts,
    ReportCouldNotBeRead,
    ReportRecogniserReturned,
    ReportGeometryFrom,
    ReportUnits,
    ReportStandingOnZero,
    ReportOriginalOrigin,
    ReportScale,
    ReportSeamRepair,
    ReportClearance,
    ReportColumnPart,
    ReportColumnTriangles,
    ReportColumnOpen,
    ReportColumnSeams,
    ReportColumnGaps,
    ReportColumnSize,
    ReportShapesClosed,
    ReportSeamsClosedSummary,
    ReportGapsFilledSummary,
    ReportRetiredNumbers,
    ReportBuiltWithSomethingMissing,
    ReportProducedNothing,
    ReportPrintingNoteTitle,
    ReportPrintingNoteBody,
    ReportPrintingNoteWithClearance,
    ReportPlateSummary,
    ReportPlateLine,
    ReportPlateColumnPlate,
    ReportPlateColumnColour,
    ReportPlateColumnPieces,
    ReportPlateColumnFootprint,
    ReportPlateDidNotFit,
    ReportPlateMissingParts,

    // The shape library: where a run's geometry came from, and how it was got.
    LibraryFolder,
    LibraryArchive,
    LibraryWebsite,
    LibraryNone,
    MsgLDrawUsingFolder,
    MsgLDrawNotALibrary,
    MsgLDrawUsingDownloaded,
    MsgLDrawFetchingPerFile,
    MsgLDrawRefused,
    MsgLDrawDownloading,
    MsgLDrawReady,

    // Running.
    MsgPagesInDocument,
    MsgReadingPages,
    MsgReadingPrintedPages,
    MsgLookingUpElements,
    MsgNoPageRange,
    MsgNoSuchFile,
    MsgNoSuchPartsList,
    MsgPageIsCatalogueOne,
    MsgPageIsCatalogueMany,
    MsgNoCataloguePages,
    MsgNoCatalogueInThisBook,
    MsgCataloguePagesFound,
    MsgShapeClosed,
    MsgShapeOpenEdges,
    MsgLookingUpSet,
    MsgSetSummary,
    MsgSuggestedRange,
    MsgEntriesSummary,
    MsgPartsListWritten,
    MsgReportWritten,
    MsgCouldNotReadEntriesOne,
    MsgCouldNotReadEntriesMany,
    MsgUnreadEntryAt,
    ReasonCouldNotReadQuantity,
    ReasonCouldNotReadPartAndColour,
    ReasonCouldNotReadEither,
    ReasonUnknownElement,
    ReasonShapeHasNoSurfaces,
    ReasonNoShapeFile,
    MsgWrittenWithoutThem,
    MsgEntriesAndParts,
    MsgWroteShapes,
    MsgClosedAndOpen,
    MsgProducedNothing,
    MsgWrotePlates,
    MsgNoPlatesRequested,
    MsgPlatesMissingParts,
    MsgCalibrationWritten,
    CalibrationTitle,
    CalibrationHow,
    CalibrationThen,
    MsgClearanceApplied,
    MsgClearanceRefusedOpen,
    MsgClearanceRefusedStillOpen,
    MsgClearanceRefusedThin,
    MsgCancelled,
    MsgError,

    // Things that go wrong, said in a way that says what to do next.
    ErrChooseDocument,
    ErrChoosePartsList,
    ErrTypeSetNumber,
    ErrNoFileAt,
    ErrScaleNotPositive,
    ErrSpacingNegative,
    ErrNotABedSize,
    ErrClearanceNeedsClosedShape,
    ErrClearanceNegative,
    ErrPartTooSmallForClearance,
    ErrPlateTooSmall,
    ErrPartTooTallForBed,
    ErrOcrUnavailable,
    ErrOcrWrongBuild,
    ErrOpenScadNotFound,
    ErrUnknownColourCode,
    ErrColourSchemeHintBrickLink,
    ErrColourSchemeHintOther,
    ErrColourHasNoBrickLinkCode,
    ErrSetCameBackEmpty,

    // The interface.
    UiTitle,
    UiTabRun,
    UiRailRuns,
    UiRailSetup,
    UiNewRun,
    UiNext,
    UiBack,
    UiStart,
    UiCancel,
    UiBrowse,
    UiInputKind,
    UiInputDocument,
    UiInputPartsList,
    UiInputSetNumber,
    UiChooseDocument,
    UiChoosePartsList,
    UiSetNumber,
    UiPageRange,
    UiPageRangeHint,
    UiScanPages,
    UiScanning,
    UiColourScheme,
    UiLanguage,
    UiSettings,
    UiEquivalentCommand,
    UiCopyCommand,
    UiCopied,
    UiGroupStages,
    UiGroupOutput,
    UiGroupGeometry,
    UiGroupLibrary,
    UiGroupPlates,
    UiGroupBehaviour,
    UiProgress,
    UiLog,
    UiShowLog,
    UiHideLog,
    UiCatalogueEmpty,
    UiFilterByColour,
    UiAllColours,
    UiSortBy,
    UiSortByPart,
    UiSortByQuantity,
    UiSortByColour,
    UiOpenShapeFile,
    UiOpenPlate,
    UiOpenFolder,
    UiWarningNotClosed,
    UiWarningThinFeature,
    UiQuantity,
    UiDone,
    UiFailed,
    UiIdle,
    UiEveryOptionHere,

    // How a run stands, and where it got to if it did not finish.
    UiStatusRunning,
    UiStatusComplete,
    UiStatusNeedsDecision,
    UiStatusFailed,
    UiStatusStopped,
    UiStoppedAt,

    // The list of runs that have happened.
    UiRunsEmpty,
    UiForget,
    UiForgetEverything,
    UiFolderMissing,

    // What a run's page says when its record is missing or from a newer build.
    UiNoManifest,
    UiNewerManifest,
    UiRunItAgain,
    UiOpenPartsList,
    UiContinueFromPartsList,

    // Finding a way through the options.
    UiSearchOptions,
    UiChangedOnly,
    UiHiddenCount,
    UiReset,

    // The open run.
    UiQuietNote,
    UiWhen,
    UiRunFolder,

    // The steps of a run, named for a screen rather than for a log.
    UiStageReadingDocument,
    UiStageLookingUpSet,
    UiStageReadingPartsList,
    UiStageWritingPartsList,
    UiStageGatheringShapes,
    UiStageBuildingShapes,
    UiStageArrangingPlates,
    UiStageWritingReport,

    // Remarks a run makes about what it found along the way.
    NoteEntriesFound,
    NoteElementTable,
    NoteNoElementTable,
    NoteElementsResolved,
    NoteElementsFromTable,
    NoteElementsFromRebrickable,
    NoteElementsFromNumber,
    NoteLearnedLettering,
    NoteLearnedSkipped,
    NoteRecoveredQuantities,
    NoteDuplicateEntry,
    NoteNoHeadingRow,
    NoteRead,
    NoteSetColourUnknown,
    NoteSetColourHasNoBrickLinkCode,
    NoteSetSparesLeftOut,
    NoteSetLinesWithoutColour,
    ReportPrinter,

    // What --help says. Kept here with everything else so that a language cannot be
    // half-applied: messages in one language and the help in another is the state these
    // tables exist to prevent.
    HelpRoot,
    HelpExtract,
    HelpBuild,
    HelpCalibration,
    HelpBricks,
    HelpRefreshColors,
    HelpArgDocument,
    HelpArgPages,
    HelpArgPartsList,
    HelpArgSizes,
    HelpArgSteps,
    HelpOptLang,
    HelpOptOutputDir,
    HelpOptAscii,
    HelpOptOffline,
    HelpOptLDrawDir,
    HelpOptApiKey,
    HelpOptListPages,
    HelpOptColorScheme,
    HelpOptElementMap,
    HelpOptSet,
    HelpOptIncludeSpares,
    HelpOptCsvOnly,
    HelpOptNoPlates,
    HelpOptDelimiter,
    HelpOptKeepOrigin,
    HelpOptScale,
    HelpOptClearance,
    HelpOptNoRepair,
    HelpOptNoSeamRepair,
    HelpOptWeldTolerance,
    HelpOptLDrawCache,
    HelpOptNoUnofficial,
    HelpOptPrinter,
    HelpOptPlateSize,
    HelpOptPlateSpacing,
    HelpOptQuiet,
    HelpOptLog,
    HelpOptPart,
    HelpOptKind,
    HelpOptNoKnobs,
    HelpOptNoStudHoles,
    HelpOptOpenScad,
    HelpOptMachineBlocks,
    HelpOptScadOnly,
    HelpOptBricksOutputDir,
    HelpOptOut,
    HelpOptRebrickableDump,

    // What the window calls each option. The flag names the option for a terminal; this names
    // it for a reader, so the window is not a list of switches only its author can use. Both
    // are shown, because a label nobody can turn into a command is half an answer.
    LabelOptCsvOnly,
    LabelOptNoPlates,
    LabelOptAscii,
    LabelOptKeepOrigin,
    LabelOptNoRepair,
    LabelOptNoSeamRepair,
    LabelOptOffline,
    LabelOptNoUnofficial,
    LabelOptScale,
    LabelOptClearance,
    LabelOptWeldTolerance,
    LabelOptPlateSpacing,
    LabelOptOutputDir,
    LabelOptElementMap,
    LabelOptLDrawDir,
    LabelOptLDrawCache,
    LabelOptPlateSize,
    LabelOptDelimiter,
    LabelOptPrinter,
    LabelOptLang,
    LabelOptApiKey,
    LabelOptLog,
    LabelOptQuiet,
    LabelOptIncludeSpares,
}
