namespace Lego2STL.Core.Text;

/// <summary>
/// Every piece of text the tool shows.
/// </summary>
/// <remarks>
/// An enum rather than loose strings so that a missing translation is a test failure instead
/// of a phrase that silently stays English. <see cref="Strings"/> holds one table per
/// language, and the suite checks that every value here appears in all of them with matching
/// placeholders.
/// </remarks>
public enum TextKey
{
    // The parts list's column headings. These follow the display language, and every
    // wording the tool has ever written is still accepted on the way back in.
    CsvId,
    CsvLegoCode,
    CsvBrickLinkCode,
    CsvColourName,
    CsvRgb,
    CsvQuantity,

    // Units and small shared words.
    Millimetres,
    On,
    Off,
    Yes,
    No,
    None,

    // Reports.
    ReportRunTitle,
    ReportShapeTitle,
    ReportPlateTitle,
    ReportInput,
    ReportPages,
    ReportColourNumbering,
    ReportReading,
    ReportEntriesRead,
    ReportPartsList,
    ReportTotals,
    ReportTotalEntries,
    ReportTotalPieces,
    ReportTotalDistinctParts,
    ReportCouldNotBeRead,
    ReportRecogniserReturned,
    ReportGeometryFrom,
    ReportUnits,
    ReportStandingOnZero,
    ReportOriginalOrigin,
    ReportScale,
    ReportSeamRepair,
    ReportClearance,
    ReportColumnPart,
    ReportColumnTriangles,
    ReportColumnOpen,
    ReportColumnSeams,
    ReportColumnSize,
    ReportShapesClosed,
    ReportSeamsClosedSummary,
    ReportRetiredNumbers,
    ReportBuiltWithSomethingMissing,
    ReportProducedNothing,
    ReportPrintingNoteTitle,
    ReportPrintingNoteBody,
    ReportPrintingNoteWithClearance,
    ReportPlateSummary,
    ReportPlateLine,
    ReportPlateColumnPlate,
    ReportPlateColumnColour,
    ReportPlateColumnPieces,
    ReportPlateColumnFootprint,
    ReportPlateDidNotFit,

    // Running.
    MsgPagesInDocument,
    MsgReadingPages,
    MsgNoPageRange,
    MsgNoSuchFile,
    MsgNoSuchPartsList,
    MsgPageIsCatalogueOne,
    MsgPageIsCatalogueMany,
    MsgNoCataloguePages,
    MsgSuggestedRange,
    MsgEntriesSummary,
    MsgPartsListWritten,
    MsgReportWritten,
    MsgCouldNotReadEntriesOne,
    MsgCouldNotReadEntriesMany,
    MsgWrittenWithoutThem,
    MsgEntriesAndParts,
    MsgWroteShapes,
    MsgClosedAndOpen,
    MsgProducedNothing,
    MsgWrotePlates,
    MsgNoPlatesRequested,
    MsgPlatesSkippedUnverified,
    MsgCalibrationWritten,
    MsgCancelled,
    MsgError,

    // Things that go wrong, said in a way that says what to do next.
    ErrClearanceNeedsClosedShape,
    ErrClearanceNegative,
    ErrPartTooSmallForClearance,
    ErrPlateTooSmall,
    ErrOcrUnavailable,
    ErrOpenScadNotFound,

    // The interface.
    UiTitle,
    UiTabInput,
    UiTabOptions,
    UiTabRun,
    UiTabCatalogue,
    UiNext,
    UiBack,
    UiStart,
    UiCancel,
    UiBrowse,
    UiInputKind,
    UiInputDocument,
    UiInputPartsList,
    UiInputSetNumber,
    UiChooseDocument,
    UiChoosePartsList,
    UiSetNumber,
    UiPageRange,
    UiPageRangeHint,
    UiScanPages,
    UiScanning,
    UiColourScheme,
    UiLanguage,
    UiSettings,
    UiEquivalentCommand,
    UiCopyCommand,
    UiCopied,
    UiGroupStages,
    UiGroupOutput,
    UiGroupGeometry,
    UiGroupLibrary,
    UiGroupPlates,
    UiGroupBehaviour,
    UiProgress,
    UiLog,
    UiShowLog,
    UiHideLog,
    UiCatalogueEmpty,
    UiFilterByColour,
    UiAllColours,
    UiSortBy,
    UiSortByPart,
    UiSortByQuantity,
    UiSortByColour,
    UiOpenShapeFile,
    UiOpenPlate,
    UiOpenFolder,
    UiWarningNotClosed,
    UiWarningThinFeature,
    UiQuantity,
    UiDone,
    UiFailed,
    UiIdle,
}
